### ISSUE TITLE
New UI and UX need 💡::🎨 Request for Major UI Changes 🚀

### ISSUE THREAD

**Issue by PatilHarshh** [PatilHarshh/Kaam-Do#3]
**### Description:**
The current user interface (UI) of our application needs significant enhancements to improve usability, accessibility, and overall user experience.

**Required Changes:**

1. Implement a new navigation system with simplified menus or sidebar navigation.
2. Update the visual design with a modern color scheme and typography.
3. Ensure responsive design across all devices, prioritizing mobile optimization.
4. Enhance accessibility features for improved inclusivity.
5. Streamline workflows by redesigning UI elements based on user feedback and analytics.

Let's work together to transform the UI of our application and deliver a more engaging and user-friendly experience for our users. 🌟

**Comment by PatilHarshh** [comment]
Required Team for Developing the UI/UX for Major Changes , Intrested !? Reply to this Issue.

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.

**Comment by r7projects-shayan** [comment]
Sir, I can solve the issue for the frontend ui/ux in a short period of time. 

I have studied about typography and graphic design so it's easier for me to integrate amazing color sense into the website to make it look magical. 

I will also keep in mind the various types of users that may visit the website so everyone's specific needs are fulfilled.

**Comment by Prithwi32** [comment]
@PatilHarshh Please could you assign me this issue under GSSoC'24

**Comment by PatilHarshh** [comment]
@Shyambarua @r7projects-shayan @Prithwi32  Can you Share the New UI for our site ? it will easy for me to decide further !

**Comment by r7projects-shayan** [comment]
@Shyambarua I will share it with you soon.

**Comment by aloku901** [comment]
@PatilHarshh Assign this issue to me for update UI if you have any figma please provide me I have done it

**Comment by rikhiltaneja** [comment]
Hi @PatilHarshh 

You have correctly identified the need of redisgning UI/UX for better usability of the website.
The requirements listed by you are completely on point to accomplish the goal of a better User Experience. I think I will be able to handle all these correctly and properly as I have previously developed projects which includes all these things.

## How will I do it?
- Navbar Redesign: A better looking and completely responsive Navbar (with drop-menus on phone width).
- Redesigning of Color Theme and Typography to make it more subtle and match with the theme of Job Seeking and Hustling Culture.
- Redisgning the boxes of Jobs Posted to make them look more appealing and updating them in a way so that those boxes contain more useful info in a concise manner.
- Updating and resdisgning the Job Uploading forms: converting it into a multi-step form which will enhance the UI by a mile and also make it seem like less over-whelming for the person who is filling it.
- Complete redesign of components related to Company Profiles so that Job seekers get better knowledge about the Company which they are applying in.
- Inclusion of Google Translate to make the website usable accessible for more number of Job Seekers.
- Redesign of About Page to clearly highlight the Goal of this website and how is it different than the others. (an interactive About Page)

All the things mentioned above will fulfill the requirements mentioned by you.

Please assign me this issue so that I can starting working on it ASAP. (under GSSOC'24)
Looking forward to a positive response.

**Comment by rikhiltaneja** [comment]
@r7projects-shayan I appreciate your efforts but the design created by you does not meet industry standards at all and would not be good according to the User Experience as well.

_Just a feedback, please don't take it in an offensive manner. 🙂_

**Comment by r7projects-shayan** [comment]
@rikhiltaneja Sure, I will recreate it, thanks for the feedback

**Comment by MehtabAsHellic** [comment]
Hi Admin,

I'm interested in contributing to your project as part of GSSoC. I've been following your work and believe my skills align well. You can find my portfolio here: (https://sites.google.com/view/uibymehtab) and LinkedIn (https://www.linkedin.com/in/mehtabarkhan/)

Thanks,
Mehtab

**Comment by Devansh1508** [comment]
Hi Admin,
I'm interested in contributing to your project as part of GSSoC. Please assign this task to me and also add the level tag to this issue.

**Comment by Caliber-Ruchi** [comment]
![Screenshot from 2024-05-11 18-16-06](https://github.com/PatilHarshh/Kaam-Do/assets/128621040/039a133b-5add-4c1b-89ca-dc0c95fd662d)

This can be further modified according to the specificness . Kindly assign this to me.

**Comment by Caliber-Ruchi** [comment]
![Screenshot from 2024-05-11 18-16-06](https://github.com/PatilHarshh/Kaam-Do/assets/128621040/22b222ee-51c2-4b8c-a04c-e59ee3068c40)

This can be further modified according to the specificness . Kindly assign it.

**Comment by PatilHarshh** [comment]
> ![Screenshot from 2024-05-11 18-16-06](https://private-user-images.githubusercontent.com/128621040/329787122-22b222ee-51c2-4b8c-a04c-e59ee3068c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjYzMDgsIm5iZiI6MTcxNTUyNjAwOCwicGF0aCI6Ii8xMjg2MjEwNDAvMzI5Nzg3MTIyLTIyYjIyMmVlLTUxYzItNGI4Yy1hMDRjLWU1OWVlMzA2OGM0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMlQxNTAwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzkyYjVmOTJjYWUyMjczOWM1MWI0NTZmODNkNmI0YTFkODI2MjMwMjFhNWJjNDFjOWMzMDI4NjliMTljODZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kk8fpDZ-wj2UYDdYyF13HcoAIZGSY07nz3Wp7AriXz8)
> 
> This can be further modified according to the specificness . Kindly assign it.


@Caliber-Ruchi  Not bad ! @r7projects-shayan @rikhiltaneja   Can we move to this and modify more to this or you have your design ready ?

**Comment by r7projects-shayan** [comment]
@PatilHarshh yes you can move to the new design

**Comment by rikhiltaneja** [comment]
@PatilHarshh , design by @Caliber-Ruchi is great! We can proceed with this and can design all other pages on the same theme.

You can assign some of the partcipants (of your choice) of this issue and then all the assignees will divide the work themselves and raise PRs.

**Comment by sourav-sm** [comment]
Hey @PatilHarshh  , I am Sourav Mohanta , 3rd year Student of NIT Durgapur, I have previously contributed to p5js (Processing Foundation) ,
I understand the issue and work on this challenging issue , Plz assign it to me

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can work on this under GSSoC'24. Lemme know :)
